# Generated by Django 5.1.7 on 2025-04-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_storeinfo_google_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram manzil'),
        ),
    ]
