# Generated by Django 5.1.7 on 2025-04-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_storeinfo_telegram_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='google_map_url',
            field=models.URLField(verbose_name='Google Map Manzili'),
        ),
    ]
