# Generated by Django 5.1.7 on 2025-04-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_storeinfo_google_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='google_map_url',
            field=models.TextField(verbose_name='Google Map Manzili'),
        ),
    ]
