# Generated by Django 5.1.7 on 2025-04-29 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_storeinfo_google_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcategory',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='aboutcategory',
            name='photo',
            field=models.ImageField(upload_to='images/display/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='aboutcategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='photo',
            field=models.ImageField(upload_to='images/display/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kichik sarlavha'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Banner sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video havola'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to='category_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Logo nomi'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='photo',
            field=models.ImageField(upload_to='images/display/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='photo',
            field=models.ImageField(upload_to='images/display/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Yangi mahsulotmi?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='images/display/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='google_map_url',
            field=models.TextField(verbose_name='Google Map manzili'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram havolasi'),
        ),
    ]
