# Generated by Django 5.2 on 2025-05-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_aboutcategory_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('name_uz', models.CharField(blank=True, max_length=150, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=150, null=True)),
                ('name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
